branches: dev

pipeline:
  build:
    image: fastscore/maker
    commands:
      - make build
      - ls -la dist
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

workspace:
  base: /_
  path: .
