fastscore:
  fleet:
    - api: model-manage
      host: 127.0.0.1
      port: 8002
    - api: engine
      host: 127.0.0.1
      port: 12001
    - api: engine
      host: 127.0.0.1
      port: 12002
    - api: engine
      host: 127.0.0.1
      port: 12003
  db:
    type: mysql
    host: 10.0.5.183
    port: 649
    username: root
    password: root
