fastscore:
  fleet:
    - api: model-manage
      host: 172.17.0.1
      port: 8002
    - api: engine
      host: 172.17.0.1
      port: 8003

  db:
    type: mysql
    host: 172.17.0.1
    port: 3306
    username: root
    password: root

