FROM alpine:3.8

RUN apk add --no-cache py2-pip python3

COPY sdk/dist /dist
COPY dist /dist
WORKDIR /dist

RUN pip2 install fastscore-*py2* &&\
	pip2 install fastscore_cli-*py2* &&\
	fastscore

RUN pip3 install fastscore-*py3* &&\
	pip3 install fastscore_cli-*py3* &&\
	fastscore
