# coding: utf-8

"""
    FastScore API (proxy)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.7
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CpuUsageInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'duration': 'float',
        'input_bytes': 'int',
        'input_records': 'int',
        'output_bytes': 'int',
        'output_records': 'int',
        'user_time': 'float',
        'kernel_time': 'float',
        'op_times': 'list[CpuUsageInfoOpTimes]',
        'jets': 'list[CpuUsageInfoJets]'
    }

    attribute_map = {
        'duration': 'duration',
        'input_bytes': 'input_bytes',
        'input_records': 'input_records',
        'output_bytes': 'output_bytes',
        'output_records': 'output_records',
        'user_time': 'user_time',
        'kernel_time': 'kernel_time',
        'op_times': 'op_times',
        'jets': 'jets'
    }

    def __init__(self, duration=None, input_bytes=None, input_records=None, output_bytes=None, output_records=None, user_time=None, kernel_time=None, op_times=None, jets=None):
        """
        CpuUsageInfo - a model defined in Swagger
        """

        self._duration = None
        self._input_bytes = None
        self._input_records = None
        self._output_bytes = None
        self._output_records = None
        self._user_time = None
        self._kernel_time = None
        self._op_times = None
        self._jets = None

        if duration is not None:
          self.duration = duration
        if input_bytes is not None:
          self.input_bytes = input_bytes
        if input_records is not None:
          self.input_records = input_records
        if output_bytes is not None:
          self.output_bytes = output_bytes
        if output_records is not None:
          self.output_records = output_records
        if user_time is not None:
          self.user_time = user_time
        if kernel_time is not None:
          self.kernel_time = kernel_time
        if op_times is not None:
          self.op_times = op_times
        if jets is not None:
          self.jets = jets

    @property
    def duration(self):
        """
        Gets the duration of this CpuUsageInfo.

        :return: The duration of this CpuUsageInfo.
        :rtype: float
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """
        Sets the duration of this CpuUsageInfo.

        :param duration: The duration of this CpuUsageInfo.
        :type: float
        """

        self._duration = duration

    @property
    def input_bytes(self):
        """
        Gets the input_bytes of this CpuUsageInfo.

        :return: The input_bytes of this CpuUsageInfo.
        :rtype: int
        """
        return self._input_bytes

    @input_bytes.setter
    def input_bytes(self, input_bytes):
        """
        Sets the input_bytes of this CpuUsageInfo.

        :param input_bytes: The input_bytes of this CpuUsageInfo.
        :type: int
        """

        self._input_bytes = input_bytes

    @property
    def input_records(self):
        """
        Gets the input_records of this CpuUsageInfo.

        :return: The input_records of this CpuUsageInfo.
        :rtype: int
        """
        return self._input_records

    @input_records.setter
    def input_records(self, input_records):
        """
        Sets the input_records of this CpuUsageInfo.

        :param input_records: The input_records of this CpuUsageInfo.
        :type: int
        """

        self._input_records = input_records

    @property
    def output_bytes(self):
        """
        Gets the output_bytes of this CpuUsageInfo.

        :return: The output_bytes of this CpuUsageInfo.
        :rtype: int
        """
        return self._output_bytes

    @output_bytes.setter
    def output_bytes(self, output_bytes):
        """
        Sets the output_bytes of this CpuUsageInfo.

        :param output_bytes: The output_bytes of this CpuUsageInfo.
        :type: int
        """

        self._output_bytes = output_bytes

    @property
    def output_records(self):
        """
        Gets the output_records of this CpuUsageInfo.

        :return: The output_records of this CpuUsageInfo.
        :rtype: int
        """
        return self._output_records

    @output_records.setter
    def output_records(self, output_records):
        """
        Sets the output_records of this CpuUsageInfo.

        :param output_records: The output_records of this CpuUsageInfo.
        :type: int
        """

        self._output_records = output_records

    @property
    def user_time(self):
        """
        Gets the user_time of this CpuUsageInfo.

        :return: The user_time of this CpuUsageInfo.
        :rtype: float
        """
        return self._user_time

    @user_time.setter
    def user_time(self, user_time):
        """
        Sets the user_time of this CpuUsageInfo.

        :param user_time: The user_time of this CpuUsageInfo.
        :type: float
        """

        self._user_time = user_time

    @property
    def kernel_time(self):
        """
        Gets the kernel_time of this CpuUsageInfo.

        :return: The kernel_time of this CpuUsageInfo.
        :rtype: float
        """
        return self._kernel_time

    @kernel_time.setter
    def kernel_time(self, kernel_time):
        """
        Sets the kernel_time of this CpuUsageInfo.

        :param kernel_time: The kernel_time of this CpuUsageInfo.
        :type: float
        """

        self._kernel_time = kernel_time

    @property
    def op_times(self):
        """
        Gets the op_times of this CpuUsageInfo.

        :return: The op_times of this CpuUsageInfo.
        :rtype: list[CpuUsageInfoOpTimes]
        """
        return self._op_times

    @op_times.setter
    def op_times(self, op_times):
        """
        Sets the op_times of this CpuUsageInfo.

        :param op_times: The op_times of this CpuUsageInfo.
        :type: list[CpuUsageInfoOpTimes]
        """

        self._op_times = op_times

    @property
    def jets(self):
        """
        Gets the jets of this CpuUsageInfo.

        :return: The jets of this CpuUsageInfo.
        :rtype: list[CpuUsageInfoJets]
        """
        return self._jets

    @jets.setter
    def jets(self, jets):
        """
        Sets the jets of this CpuUsageInfo.

        :param jets: The jets of this CpuUsageInfo.
        :type: list[CpuUsageInfoJets]
        """

        self._jets = jets

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CpuUsageInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
