# coding: utf-8

"""
    FastScore API (proxy)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.7
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class HealthInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'release': 'str',
        'built_on': 'str'
    }

    attribute_map = {
        'id': 'id',
        'release': 'release',
        'built_on': 'built_on'
    }

    def __init__(self, id=None, release=None, built_on=None):
        """
        HealthInfo - a model defined in Swagger
        """

        self._id = None
        self._release = None
        self._built_on = None

        if id is not None:
          self.id = id
        if release is not None:
          self.release = release
        if built_on is not None:
          self.built_on = built_on

    @property
    def id(self):
        """
        Gets the id of this HealthInfo.

        :return: The id of this HealthInfo.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this HealthInfo.

        :param id: The id of this HealthInfo.
        :type: str
        """

        self._id = id

    @property
    def release(self):
        """
        Gets the release of this HealthInfo.

        :return: The release of this HealthInfo.
        :rtype: str
        """
        return self._release

    @release.setter
    def release(self, release):
        """
        Sets the release of this HealthInfo.

        :param release: The release of this HealthInfo.
        :type: str
        """

        self._release = release

    @property
    def built_on(self):
        """
        Gets the built_on of this HealthInfo.

        :return: The built_on of this HealthInfo.
        :rtype: str
        """
        return self._built_on

    @built_on.setter
    def built_on(self, built_on):
        """
        Sets the built_on of this HealthInfo.

        :param built_on: The built_on of this HealthInfo.
        :type: str
        """

        self._built_on = built_on

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, HealthInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
