# coding: utf-8

"""
    FastScore API (proxy)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.7
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse2002(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'tap': 'str',
        'permanent': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'tap': 'tap',
        'permanent': 'permanent'
    }

    def __init__(self, id=None, tap=None, permanent=None):
        """
        InlineResponse2002 - a model defined in Swagger
        """

        self._id = None
        self._tap = None
        self._permanent = None

        if id is not None:
          self.id = id
        if tap is not None:
          self.tap = tap
        if permanent is not None:
          self.permanent = permanent

    @property
    def id(self):
        """
        Gets the id of this InlineResponse2002.

        :return: The id of this InlineResponse2002.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this InlineResponse2002.

        :param id: The id of this InlineResponse2002.
        :type: int
        """

        self._id = id

    @property
    def tap(self):
        """
        Gets the tap of this InlineResponse2002.

        :return: The tap of this InlineResponse2002.
        :rtype: str
        """
        return self._tap

    @tap.setter
    def tap(self, tap):
        """
        Sets the tap of this InlineResponse2002.

        :param tap: The tap of this InlineResponse2002.
        :type: str
        """

        self._tap = tap

    @property
    def permanent(self):
        """
        Gets the permanent of this InlineResponse2002.

        :return: The permanent of this InlineResponse2002.
        :rtype: bool
        """
        return self._permanent

    @permanent.setter
    def permanent(self, permanent):
        """
        Sets the permanent of this InlineResponse2002.

        :param permanent: The permanent of this InlineResponse2002.
        :type: bool
        """

        self._permanent = permanent

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse2002):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
