# coding: utf-8

"""
    FastScore API (proxy)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.7
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse200(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'tap': 'str',
        'active': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'tap': 'tap',
        'active': 'active'
    }

    def __init__(self, id=None, tap=None, active=None):
        """
        InlineResponse200 - a model defined in Swagger
        """

        self._id = None
        self._tap = None
        self._active = None

        self.id = id
        self.tap = tap
        self.active = active

    @property
    def id(self):
        """
        Gets the id of this InlineResponse200.

        :return: The id of this InlineResponse200.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this InlineResponse200.

        :param id: The id of this InlineResponse200.
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def tap(self):
        """
        Gets the tap of this InlineResponse200.

        :return: The tap of this InlineResponse200.
        :rtype: str
        """
        return self._tap

    @tap.setter
    def tap(self, tap):
        """
        Sets the tap of this InlineResponse200.

        :param tap: The tap of this InlineResponse200.
        :type: str
        """
        if tap is None:
            raise ValueError("Invalid value for `tap`, must not be `None`")

        self._tap = tap

    @property
    def active(self):
        """
        Gets the active of this InlineResponse200.

        :return: The active of this InlineResponse200.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """
        Sets the active of this InlineResponse200.

        :param active: The active of this InlineResponse200.
        :type: bool
        """
        if active is None:
            raise ValueError("Invalid value for `active`, must not be `None`")

        self._active = active

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse200):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
