# coding: utf-8

"""
    FastScore API (proxy)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.7
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse2003(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rps': 'float',
        'mbps': 'float'
    }

    attribute_map = {
        'rps': 'rps',
        'mbps': 'mbps'
    }

    def __init__(self, rps=None, mbps=None):
        """
        InlineResponse2003 - a model defined in Swagger
        """

        self._rps = None
        self._mbps = None

        self.rps = rps
        self.mbps = mbps

    @property
    def rps(self):
        """
        Gets the rps of this InlineResponse2003.
        Records per second

        :return: The rps of this InlineResponse2003.
        :rtype: float
        """
        return self._rps

    @rps.setter
    def rps(self, rps):
        """
        Sets the rps of this InlineResponse2003.
        Records per second

        :param rps: The rps of this InlineResponse2003.
        :type: float
        """
        if rps is None:
            raise ValueError("Invalid value for `rps`, must not be `None`")

        self._rps = rps

    @property
    def mbps(self):
        """
        Gets the mbps of this InlineResponse2003.
        Megabytes per second

        :return: The mbps of this InlineResponse2003.
        :rtype: float
        """
        return self._mbps

    @mbps.setter
    def mbps(self, mbps):
        """
        Sets the mbps of this InlineResponse2003.
        Megabytes per second

        :param mbps: The mbps of this InlineResponse2003.
        :type: float
        """
        if mbps is None:
            raise ValueError("Invalid value for `mbps`, must not be `None`")

        self._mbps = mbps

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse2003):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
