# coding: utf-8

"""
    FastScore API (proxy)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.7
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InstanceInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'api': 'str',
        'host': 'str',
        'port': 'int',
        'release': 'str',
        'built_on': 'str',
        'health': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'api': 'api',
        'host': 'host',
        'port': 'port',
        'release': 'release',
        'built_on': 'built_on',
        'health': 'health'
    }

    def __init__(self, id=None, name=None, api=None, host=None, port=None, release=None, built_on=None, health=None):
        """
        InstanceInfo - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self._api = None
        self._host = None
        self._port = None
        self._release = None
        self._built_on = None
        self._health = None

        if id is not None:
          self.id = id
        if name is not None:
          self.name = name
        if api is not None:
          self.api = api
        if host is not None:
          self.host = host
        if port is not None:
          self.port = port
        if release is not None:
          self.release = release
        if built_on is not None:
          self.built_on = built_on
        if health is not None:
          self.health = health

    @property
    def id(self):
        """
        Gets the id of this InstanceInfo.

        :return: The id of this InstanceInfo.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this InstanceInfo.

        :param id: The id of this InstanceInfo.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this InstanceInfo.

        :return: The name of this InstanceInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this InstanceInfo.

        :param name: The name of this InstanceInfo.
        :type: str
        """

        self._name = name

    @property
    def api(self):
        """
        Gets the api of this InstanceInfo.

        :return: The api of this InstanceInfo.
        :rtype: str
        """
        return self._api

    @api.setter
    def api(self, api):
        """
        Sets the api of this InstanceInfo.

        :param api: The api of this InstanceInfo.
        :type: str
        """

        self._api = api

    @property
    def host(self):
        """
        Gets the host of this InstanceInfo.

        :return: The host of this InstanceInfo.
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host):
        """
        Sets the host of this InstanceInfo.

        :param host: The host of this InstanceInfo.
        :type: str
        """

        self._host = host

    @property
    def port(self):
        """
        Gets the port of this InstanceInfo.

        :return: The port of this InstanceInfo.
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """
        Sets the port of this InstanceInfo.

        :param port: The port of this InstanceInfo.
        :type: int
        """

        self._port = port

    @property
    def release(self):
        """
        Gets the release of this InstanceInfo.

        :return: The release of this InstanceInfo.
        :rtype: str
        """
        return self._release

    @release.setter
    def release(self, release):
        """
        Sets the release of this InstanceInfo.

        :param release: The release of this InstanceInfo.
        :type: str
        """

        self._release = release

    @property
    def built_on(self):
        """
        Gets the built_on of this InstanceInfo.

        :return: The built_on of this InstanceInfo.
        :rtype: str
        """
        return self._built_on

    @built_on.setter
    def built_on(self, built_on):
        """
        Sets the built_on of this InstanceInfo.

        :param built_on: The built_on of this InstanceInfo.
        :type: str
        """

        self._built_on = built_on

    @property
    def health(self):
        """
        Gets the health of this InstanceInfo.

        :return: The health of this InstanceInfo.
        :rtype: str
        """
        return self._health

    @health.setter
    def health(self, health):
        """
        Sets the health of this InstanceInfo.

        :param health: The health of this InstanceInfo.
        :type: str
        """

        self._health = health

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InstanceInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
