# coding: utf-8

"""
    FastScore API (proxy)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.7
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ManifoldInfoModel(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'type': 'str',
        'source': 'str',
        'attachments': 'list[str]'
    }

    attribute_map = {
        'name': 'name',
        'type': 'type',
        'source': 'source',
        'attachments': 'attachments'
    }

    def __init__(self, name=None, type=None, source=None, attachments=None):
        """
        ManifoldInfoModel - a model defined in Swagger
        """

        self._name = None
        self._type = None
        self._source = None
        self._attachments = None

        if name is not None:
          self.name = name
        if type is not None:
          self.type = type
        if source is not None:
          self.source = source
        if attachments is not None:
          self.attachments = attachments

    @property
    def name(self):
        """
        Gets the name of this ManifoldInfoModel.

        :return: The name of this ManifoldInfoModel.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ManifoldInfoModel.

        :param name: The name of this ManifoldInfoModel.
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """
        Gets the type of this ManifoldInfoModel.

        :return: The type of this ManifoldInfoModel.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this ManifoldInfoModel.

        :param type: The type of this ManifoldInfoModel.
        :type: str
        """

        self._type = type

    @property
    def source(self):
        """
        Gets the source of this ManifoldInfoModel.

        :return: The source of this ManifoldInfoModel.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """
        Sets the source of this ManifoldInfoModel.

        :param source: The source of this ManifoldInfoModel.
        :type: str
        """

        self._source = source

    @property
    def attachments(self):
        """
        Gets the attachments of this ManifoldInfoModel.

        :return: The attachments of this ManifoldInfoModel.
        :rtype: list[str]
        """
        return self._attachments

    @attachments.setter
    def attachments(self, attachments):
        """
        Sets the attachments of this ManifoldInfoModel.

        :param attachments: The attachments of this ManifoldInfoModel.
        :type: list[str]
        """

        self._attachments = attachments

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ManifoldInfoModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
