fastscore:
  fleet:
    - api: model-manage
      host: dev-2
      port: 8002
    - api: engine
      host: dev-2
      port: 8003
  db:
    type: mysql
    host: localhost
    port: 3306
    username: root
    password: root
