# coding: utf-8

"""
    FastScore API (proxy)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.7
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ActiveStreamInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'slot': 'int',
        'name': 'str',
        'descriptor': 'object',
        'eof': 'bool'
    }

    attribute_map = {
        'slot': 'slot',
        'name': 'name',
        'descriptor': 'descriptor',
        'eof': 'eof'
    }

    def __init__(self, slot=None, name=None, descriptor=None, eof=None):
        """
        ActiveStreamInfo - a model defined in Swagger
        """

        self._slot = None
        self._name = None
        self._descriptor = None
        self._eof = None

        if slot is not None:
          self.slot = slot
        if name is not None:
          self.name = name
        if descriptor is not None:
          self.descriptor = descriptor
        if eof is not None:
          self.eof = eof

    @property
    def slot(self):
        """
        Gets the slot of this ActiveStreamInfo.

        :return: The slot of this ActiveStreamInfo.
        :rtype: int
        """
        return self._slot

    @slot.setter
    def slot(self, slot):
        """
        Sets the slot of this ActiveStreamInfo.

        :param slot: The slot of this ActiveStreamInfo.
        :type: int
        """

        self._slot = slot

    @property
    def name(self):
        """
        Gets the name of this ActiveStreamInfo.

        :return: The name of this ActiveStreamInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ActiveStreamInfo.

        :param name: The name of this ActiveStreamInfo.
        :type: str
        """

        self._name = name

    @property
    def descriptor(self):
        """
        Gets the descriptor of this ActiveStreamInfo.

        :return: The descriptor of this ActiveStreamInfo.
        :rtype: object
        """
        return self._descriptor

    @descriptor.setter
    def descriptor(self, descriptor):
        """
        Sets the descriptor of this ActiveStreamInfo.

        :param descriptor: The descriptor of this ActiveStreamInfo.
        :type: object
        """

        self._descriptor = descriptor

    @property
    def eof(self):
        """
        Gets the eof of this ActiveStreamInfo.

        :return: The eof of this ActiveStreamInfo.
        :rtype: bool
        """
        return self._eof

    @eof.setter
    def eof(self, eof):
        """
        Sets the eof of this ActiveStreamInfo.

        :param eof: The eof of this ActiveStreamInfo.
        :type: bool
        """

        self._eof = eof

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ActiveStreamInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
