# coding: utf-8

"""
    FastScore API (proxy)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.7
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ActiveModelInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'mtype': 'str',
        'source': 'str',
        'slots': 'list[SlotInfo]',
        'attachments': 'list[str]',
        'snapshots': 'str',
        'jets': 'list[JetInfo]'
    }

    attribute_map = {
        'name': 'name',
        'mtype': 'mtype',
        'source': 'source',
        'slots': 'slots',
        'attachments': 'attachments',
        'snapshots': 'snapshots',
        'jets': 'jets'
    }

    def __init__(self, name=None, mtype=None, source=None, slots=None, attachments=None, snapshots=None, jets=None):
        """
        ActiveModelInfo - a model defined in Swagger
        """

        self._name = None
        self._mtype = None
        self._source = None
        self._slots = None
        self._attachments = None
        self._snapshots = None
        self._jets = None

        if name is not None:
          self.name = name
        if mtype is not None:
          self.mtype = mtype
        if source is not None:
          self.source = source
        if slots is not None:
          self.slots = slots
        if attachments is not None:
          self.attachments = attachments
        if snapshots is not None:
          self.snapshots = snapshots
        if jets is not None:
          self.jets = jets

    @property
    def name(self):
        """
        Gets the name of this ActiveModelInfo.

        :return: The name of this ActiveModelInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ActiveModelInfo.

        :param name: The name of this ActiveModelInfo.
        :type: str
        """

        self._name = name

    @property
    def mtype(self):
        """
        Gets the mtype of this ActiveModelInfo.

        :return: The mtype of this ActiveModelInfo.
        :rtype: str
        """
        return self._mtype

    @mtype.setter
    def mtype(self, mtype):
        """
        Sets the mtype of this ActiveModelInfo.

        :param mtype: The mtype of this ActiveModelInfo.
        :type: str
        """

        self._mtype = mtype

    @property
    def source(self):
        """
        Gets the source of this ActiveModelInfo.

        :return: The source of this ActiveModelInfo.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """
        Sets the source of this ActiveModelInfo.

        :param source: The source of this ActiveModelInfo.
        :type: str
        """

        self._source = source

    @property
    def slots(self):
        """
        Gets the slots of this ActiveModelInfo.

        :return: The slots of this ActiveModelInfo.
        :rtype: list[SlotInfo]
        """
        return self._slots

    @slots.setter
    def slots(self, slots):
        """
        Sets the slots of this ActiveModelInfo.

        :param slots: The slots of this ActiveModelInfo.
        :type: list[SlotInfo]
        """

        self._slots = slots

    @property
    def attachments(self):
        """
        Gets the attachments of this ActiveModelInfo.

        :return: The attachments of this ActiveModelInfo.
        :rtype: list[str]
        """
        return self._attachments

    @attachments.setter
    def attachments(self, attachments):
        """
        Sets the attachments of this ActiveModelInfo.

        :param attachments: The attachments of this ActiveModelInfo.
        :type: list[str]
        """

        self._attachments = attachments

    @property
    def snapshots(self):
        """
        Gets the snapshots of this ActiveModelInfo.

        :return: The snapshots of this ActiveModelInfo.
        :rtype: str
        """
        return self._snapshots

    @snapshots.setter
    def snapshots(self, snapshots):
        """
        Sets the snapshots of this ActiveModelInfo.

        :param snapshots: The snapshots of this ActiveModelInfo.
        :type: str
        """

        self._snapshots = snapshots

    @property
    def jets(self):
        """
        Gets the jets of this ActiveModelInfo.

        :return: The jets of this ActiveModelInfo.
        :rtype: list[JetInfo]
        """
        return self._jets

    @jets.setter
    def jets(self, jets):
        """
        Sets the jets of this ActiveModelInfo.

        :param jets: The jets of this ActiveModelInfo.
        :type: list[JetInfo]
        """

        self._jets = jets

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ActiveModelInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
